asyncapi/saunter

- src/Saunter/AsyncApiSchema/v2/MessageBindings.cs
- src/Saunter/Generation/AsyncApiDocumentGenerator.cs
- src/Saunter/Generation/AsyncApiDocumentGeneratorOptions.cs
- src/Saunter/Generation/Filters/IChannelItemFilter.cs
New extension point IChannelItemFilter. Will be applied to each added channel.
> IChannelItemFilter

- Saunter.sln
- src/Saunter/AsyncApiSchema/v2/Components.cs
- src/Saunter/AsyncApiSchema/v2/ISchema.cs
- src/Saunter/AsyncApiSchema/v2/MessageTrait.cs
- src/Saunter/AsyncApiSchema/v2/OperationTrait.cs
- src/Saunter/AsyncApiSchema/v2/Reference.cs
- src/Saunter/Generation/AsyncApiDocumentGeneratorOptions.cs
- src/Saunter/Properties/AssemblyInfo.cs
- src/Saunter/Utils/Reflection.cs
- test/Saunter.Tests/Generation/OperationTraitsTests.cs
- test/Saunter.Tests/TestProviderFactory.cs
- test/Saunter.Tests/UnitTest1.cs
See OperationTraitsTests for example usage
Fixes #5
> Add OperationTraits and MessageTraits.

- src/Saunter/Generation/SchemaGeneration/SchemaGenerator.cs
- src/Saunter/Utils/Reflection.cs
- test/Saunter.Tests/Utils/ReflectionTests.cs
Adding `TimeSpan` as a primitive
> Add TimeSpan as a primitive

- CONTRIBUTING.md
- README.md
- src/Saunter/Generation/SchemaGeneration/SchemaGenerator.cs
- src/Saunter/Utils/Reflection.cs
- test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs
- test/Saunter.Tests/Utils/ReflectionTests.cs
> Support for System.Guid

- src/Saunter/AsyncApiOptions.cs
- src/Saunter/AsyncApiSchema/v2/ComponentFieldName.cs
- src/Saunter/Generation/DefaultSchemaIdFactory.cs
- test/Saunter.Tests/Generation/DefaultSchemaIdFactoryTests.cs
- test/Saunter.Tests/Generation/DocumentGeneratorTests/ClassAttributesTests.cs
> Added smarter default SchemaIdSelector

- examples/StreetlightsAPI/StreetlightsAPI.csproj
> Upgraded example to .NETCore 3.1

- src/Saunter/AsyncApiEndpointRouteBuilderExtensions.cs
- src/Saunter/Saunter.csproj
implementation for feature request #33
> add support for netstandard2.0

- .github/workflows/ci.yaml
> Make CI workflow run on pull requests

- src/Saunter/AsyncApiOptions.cs
- src/Saunter/Generation/SchemaGeneration/SchemaGenerator.cs
- test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs
implementation for feature request #34
> use the propertyname selector to determine the membername

- src/Saunter/Generation/SchemaGeneration/SchemaGenerator.cs
- test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs
> Fix use membername for required members

- src/Saunter/AsyncApiMiddleware.cs
- src/Saunter/Saunter.csproj
> Fix missing netstandard excludes

- src/Saunter/AsyncApiOptions.cs
- src/Saunter/Generation/SchemaGeneration/SchemaGenerator.cs
- test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs
> Align propertyname handling

- src/Saunter/AsyncApiOptions.cs
- src/Saunter/Generation/SchemaGeneration/SchemaGenerator.cs
- test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs
> Ignore fields marked with jsonignore

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- examples/StreetlightsAPI/Program.cs
- examples/StreetlightsAPI/StreetlightsAPI.csproj
- src/Saunter/AsyncApiEndpointRouteBuilderExtensions.cs
- src/Saunter/AsyncApiMiddleware.cs
- src/Saunter/AsyncApiSchema/v2/Servers.cs
- src/Saunter/AsyncApiSchema/v2/ServersFieldName.cs
- src/Saunter/Saunter.csproj
- src/Saunter/Utils/DictionaryKeyToStringConverter.cs
- test/Saunter.Tests/Saunter.Tests.csproj
- test/Saunter.Tests/Utils/JsonConverterTests.cs
* Exclude AspNetCore stuff from netstandard build
* Fix JSON serializer for net5.0
* Upgrade non-Microsoft.Extensions.* dependencies
Fixes #61
> Target netcoreapp3.1, net5.0, netstandard2.0

- src/Saunter/AsyncApiSchema/v2/Bindings/Amqp/AmqpChannelBinding.cs
> Add vhost to AMQP channel bindings.

- src/Saunter/AsyncApiSchema/v2/Server.cs
> Add a list of most common server protocols

- src/Saunter/AsyncApiEndpointRouteBuilderExtensions.cs
> Allow customize the title of the documentation page.

- src/Saunter/AsyncApiSchema/v2/ISchema.cs
- src/Saunter/Attributes/DiscriminatorAttribute.cs
- src/Saunter/Attributes/DiscriminatorSubTypeAttribute.cs
- src/Saunter/Generation/SchemaGeneration/SchemaGenerator.cs
- test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs
> Add code-first discriminator support

- CHANGELOG.md
- src/Saunter/Utils/Reflection.cs
- test/Saunter.Tests/Utils/ReflectionTests.cs
> Treat DateTimeOffset same as DateTime

- README.md
> Document JSON Schema Settings

- CHANGELOG.md
- README.md
- src/Saunter/AsyncApiSchema/v2/AsyncApiDocument.cs
- src/Saunter/AsyncApiSchema/v2/Message.cs
- src/Saunter/AsyncApiSchema/v2/SecurityScheme.cs
> AsyncAPI spec version 2.1.0

- examples/StreetlightsAPI/API.cs
- examples/StreetlightsAPI/Messaging.cs
- examples/StreetlightsAPI/Program.cs
- examples/StreetlightsAPI/README.md
* Better documentation for how to build & run the project
* Implement PublishOperation and SubscribeOperation the right way round
Fixes #118
> Example project improvements

- examples/StreetlightsAPI/Messaging.cs
- examples/StreetlightsAPI/Program.cs
- src/Saunter/AsyncApiMiddleware.cs
- src/Saunter/AsyncApiOptions.cs
- src/Saunter/Generation/DocumentGenerator.cs
- src/Saunter/Generation/SchemaGeneration/AsyncApiSchemaResolver.cs
- src/Saunter/Saunter.csproj
- src/Saunter/Serialization/IAsyncApiDocumentSerializer.cs
- src/Saunter/Serialization/NewtonsoftAsyncApiDocumentSerializer.cs
- test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs
- test/Saunter.Tests/UI/EmbeddedResourceTests.cs
- test/Saunter.Tests/Utils/SerializerTests.cs
Just some suggestions, please wait with merge.
Please check this and let's discuss :-)
> Some improvements

- src/Saunter/AsyncApiOptions.cs
- src/Saunter/Serialization/NewtonsoftAsyncApiDocumentSerializer.cs
- test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs
Hoping to close the JSON-Schema nullable format issue once and for all.
Related issues/discussions/pulls:
* https://github.com/tehmantra/saunter/issues/117
* https://github.com/tehmantra/saunter/pull/113
* https://github.com/tehmantra/saunter/pull/103#issuecomment-893267360
* https://github.com/tehmantra/saunter/issues/60
> Switch from SchemaType.OpenApi3 to SchemaType.JsonSchema

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- Saunter.sln
- examples/StreetlightsAPI/StreetlightsAPI.csproj
- src/Saunter.UI/package-lock.json
- src/Saunter.UI/package.json
- src/Saunter/AsyncApiEndpointRouteBuilderExtensions.cs
- src/Saunter/AsyncApiMiddleware.cs
- src/Saunter/Saunter.csproj
- src/Saunter/UI/AsyncApiUiMiddleware.cs
- src/Saunter/UI/index.html
- src/Saunter/Utils/RouteMatchingExtensions.cs
- test/Saunter.IntegrationTests.ReverseProxy/Saunter.IntegrationTests.ReverseProxy.csproj
- test/Saunter.Tests/Generation/SchemaGeneration/SchemaGenerationTests.cs
- test/Saunter.Tests/Saunter.Tests.csproj
See https://github.com/tehmantra/saunter/pull/132
> Target net6.0, update all dependencies to latest

- src/Saunter/Saunter.csproj
> use embedded nuget readme

- src/Saunter/Generation/DocumentGenerator.cs
- src/Saunter/Utils/ChannelItemExtensions.cs
> Allow same channel to be used from multiple different classes

- src/Saunter/AsyncApiSchema/v2/AsyncApiDocument.cs
- src/Saunter/AsyncApiSchema/v2/Message.cs
- src/Saunter/Attributes/MessageAttribute.cs
- src/Saunter/Generation/DocumentGenerator.cs
* Saunter now generates v2.4.0 format AsyncAPI document
* Added messageId to Message and MessageAttribute
> AsyncAPI v2.4.0

- src/Saunter/Saunter.csproj
Update NJsonSchema package reference to latest version
> Update nuget dependecies

- src/Saunter/Attributes/MessageAttribute.cs
- src/Saunter/Generation/DocumentGenerator.cs
- src/Saunter/Generation/SchemaGeneration/AsyncApiSchemaResolver.cs
- test/Saunter.Tests/Generation/DocumentGeneratorTests/ClassAttributesTests.cs
add support for message headers: #150
> add support for message headers

- CODEOWNERS
> Add yurvon-screamo to CODEOWNERS

- src/Saunter/AsyncApiSchema/v2/Bindings/ChannelBindings.cs
- src/Saunter/AsyncApiSchema/v2/Bindings/MessageBindings.cs
- src/Saunter/AsyncApiSchema/v2/Bindings/OperationBindings.cs
- src/Saunter/AsyncApiSchema/v2/Bindings/Pulsar/PulsarChannelBinding.cs
- src/Saunter/AsyncApiSchema/v2/Bindings/Pulsar/PulsarMessageBinding.cs
- src/Saunter/AsyncApiSchema/v2/Bindings/Pulsar/PulsarOperationBinding.cs
- src/Saunter/AsyncApiSchema/v2/Bindings/Pulsar/PulsarServerBinding.cs
- src/Saunter/AsyncApiSchema/v2/Bindings/Pulsar/README.md
- src/Saunter/AsyncApiSchema/v2/Bindings/ServerBindings.cs
- test/Saunter.Tests/Generation/DocumentGeneratorTests/InterfaceAttributeTests.cs
**Description**
Added pulsar binding
> chore: add pulsar binding

- CODEOWNERS
I regretfully have not had the time to put in the effort i set out for. 
So I am officially stepping down as a maintainer of saunter
> Stepping down as maintainer
